apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-app
  template:
    metadata:
      labels:
        app: chat-app
    spec:
      containers:
      - name: chat-app
        image: 123456789.dkr.ecr.ap-south-1.amazonaws.com/chat-app:latest
        ports:
        - containerPort: 3000